import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import Geocode from 'react-geocode';
import Map from '../components/Map';
import OverlayBox from '../components/OverlayBox';
Geocode.setApiKey({});
Geocode.setLanguage('en');
export default function Home({ allDates }) {
  const getAddress = async (long, lat) => {
    try {
      const response = await Geocode.fromLatLng(lat, long);
      console.log(response.results[0].formatted_address);
    } catch (err) {
      console.log(err);
    }
  };
  const getCoordinates = async (address) => {
    const response = await Geocode.fromAddress(address);
    const { lat, lng } = await response.results[0].geometry.location;
  };
  const [newLong, setNewLong] = useState(0);
  const [newLat, setNewLat] = useState(0);
  const [story, setStory] = useState('');
  const [newStory, setNewStory] = useState('');
  const [markers, setMarkers] = useState(allDates.data);
  const [isLoaded, setIsLoaded] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Google API Test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <OverlayBox
        newStory={newStory}
        setNewStory={setNewStory}
        story={story}
        newLat={newLat}
        setNewLat={setNewLat}
        newLong={newLong}
        setNewLong={setNewLong}
      />
      {isLoaded ? (
        <h1 style={{ fontSize: '100px' }}>LOADING</h1>
      ) : (
        <Map data={markers} setStory={setStory} />
      )}
    </div>
  );
}

export async function getServerSideProps() {
  let response = await fetch('http:/localhost:3000/api/finddates', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });
  let allDates = await response.json();
  return {
    props: { allDates },
  };
}
